# Generated by Django 6.1 on 2026-09-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled_start', models.DateTimeField()),
                ('budgeted_minutes', models.PositiveIntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_chore_instances', to='people.person')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chores.chore')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_chore_instances', to='people.person')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chores.weeklyassignmenttemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'date'), name='unique_template_date')],
            },
        ),
    ]
