# Generated by Django 6.1 on 2026-09-02 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_choreinstance'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField()),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('chore_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='chores.choreinstance')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person')),
            ],
        ),
    ]
