# Generated by Django 6.1 on 2026-09-02 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_timelog'),
        ('people', '0002_person_daily_budget_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedAssignmentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('proposed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_assignment_changes', to='people.person')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chores.chore')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_changes_proposed', to='people.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_changes_reviewed', to='people.person')),
                ('target_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_changes', to='chores.weeklyassignmenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedBudgetChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_budget_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('weekly_budget_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('proposed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_budget_changes', to='people.person')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_changes_proposed', to='people.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_changes_reviewed', to='people.person')),
            ],
        ),
    ]
