# Generated by Django 6.1 on 2026-09-02 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_proposedassignmentchange_proposedbudgetchange'),
        ('people', '0002_person_daily_budget_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swapped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chore_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_logs', to='chores.choreinstance')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swaps_from', to='people.person')),
                ('swapped_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swaps_performed', to='people.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swaps_to', to='people.person')),
            ],
        ),
    ]
