# Generated by Django 6.1 on 2026-09-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='daily_budget_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='weekly_budget_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
