from django.contrib import admin

from .models import (
    Chore,
    ChoreInstance,
    ProposedAssignmentChange,
    ProposedBudgetChange,
    WeeklyAssignmentTemplate,
)


@admin.register(Chore)
class ChoreAdmin(admin.ModelAdmin):
    list_display = ("name", "default_duration_minutes", "is_active")


@admin.register(WeeklyAssignmentTemplate)
class WeeklyAssignmentTemplateAdmin(admin.ModelAdmin):
    list_display = ("chore", "assigned_to", "day_of_week", "start_time", "duration_minutes")


@admin.register(ChoreInstance)
class ChoreInstanceAdmin(admin.ModelAdmin):
    """Read-only-ish view: instances are generated by
    `chores.services.ensure_instances_generated`, not created or edited
    by hand, so this is here for debugging/visibility only.
    """

    list_display = (
        "date",
        "chore",
        "assigned_person",
        "scheduled_start",
        "budgeted_minutes",
        "is_done",
        "template",
    )
    list_filter = ("date", "is_done", "assigned_person")
    readonly_fields = [field.name for field in ChoreInstance._meta.fields]

    def has_add_permission(self, request):
        return False


@admin.register(ProposedAssignmentChange)
class ProposedAssignmentChangeAdmin(admin.ModelAdmin):
    list_display = (
        "chore",
        "assigned_to",
        "day_of_week",
        "status",
        "proposed_by",
        "proposed_at",
    )
    list_filter = ("status",)


@admin.register(ProposedBudgetChange)
class ProposedBudgetChangeAdmin(admin.ModelAdmin):
    list_display = (
        "person",
        "daily_budget_minutes",
        "weekly_budget_minutes",
        "status",
        "proposed_by",
        "proposed_at",
    )
    list_filter = ("status",)
